### ISSUE TITLE
Testing the Models

### ISSUE THREAD

**Issue by Cemalhas** [lafeat/apbench#1]
Hello,

I am writing to you regarding the paper "APBench: A Unified Benchmark for Availability Poisoning Attacks and Defenses"
I have to write my thesis and came across your paper. I wanted to run the Git-Repo but I have some problems. Starting with the Scripts i use Google Colab for the Project. So there are some module errors because it don´t recognize some modules. The Second issue is with the training, the training takes too long and I can't set the batch size.

Nevertheless, I have trained some models, but I cannot visualize them... do you have a script that you used to visualize the models?

**Comment by Tianyue818** [comment]
Hi,
As for the "it don´t recognize some modules. " problem, it might be related to module imports in python sub-folders. We will check the code and update soon. Training times depend on defense selection and training epochs. If you choose defense of AVATAR or U-max may lead to longer training times. You can change batch size in get_loader (in util.py), and we will update the code to simplify this process.

**Comment by Tianyue818** [comment]
As we checked the code, the main issue about modules is jax-related module.
So for better evaluations, you can use the open-source poisoned NTGA CIFAR-10 ([NTGA](https://github.com/lionelmessi6410/ntga)), although this requires modifications to the format of the poisoned data.
We have added the batch size in the training script.
For visualization scripts, we're not going to release the script. You can refer to the relevant code of each visualization method (e.g. [t-SNE](https://github.com/mxl1990/tsne-pytorch), [Grad-cam](https://github.com/ramprs/grad-cam), etc.). If you're still encountering difficulties, you can email me for help.
